apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana-ingress
  namespace: monitoring
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    #metallb.io/address-pool: ip-address-pool-tailscale
spec:
  ingressClassName: traefik
  #tls:
  #- hosts:
  #  - callandor.tailcdecb.ts.net
  #  secretName: callandor-tailscale-tls
  rules:
  - host: cbrz.dev
    http:
      paths:
      - path: /grafana
        pathType: Prefix
        backend:
          service:
            name: monitoring-grafana
            port:
              number: 80
