prometheus:
  prometheusSpec:
    retention: 30d

grafana:
  admin:
    existingSecret: monitoring-grafana
    userKey: admin-user
    passwordKey: admin-password

  grafana.ini:
    server:
      domain: k8s-node-primary.your-tailnet.ts.net
      root_url: "%(protocol)s://%(domain)s/grafana/"
      serve_from_sub_path: true

  additionalDataSources:
    - name: Loki
      type: loki
      access: proxy
      url: http://loki.monitoring.svc.cluster.local:3100
      jsonData:
        maxLines: 1000
