# yaml-language-server: $schema=https://json.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: traefik-private

helmCharts:
  - name: traefik
    repo: https://traefik.github.io/charts
    version: 28.0.0
    releaseName: traefik-private
    valuesFile: values.yaml

resources:
  - traefik-clusterrole.yaml
  - traefik-clusterrolebinding.yaml
