ingressRoute:
  dashboard:
    enabled: true
    domain: callandor.tailcdecb.ts.net
    matchRule: Host(`callandor.tailcdecb.ts.net`) && (PathPrefix(`/dashboard`) || PathPrefix(`/api`))
    entryPoints:
      - websecure
    rules:
      - host: callandor.tailcdecb.ts.net
        http:
          paths:
            - path: /dashboard
              pathType: Prefix
  tls:
    secretName: callandor-tailscale-tls
