image:
  tag: "3.6.13"

deployment:
  kind: Deployment
  replicas: 1
  strategy:
    type: Recreate

ports:
  web:
    port: 80
    exposedPort: 80

providers:
  kubernetesGateway:
    enabled: true
  kubernetesCRD:
    enabled: true
    allowCrossNamespace: true
  kubernetesIngress:
    enabled: true
    ingressClass: traefik
    ingressEndpoint:
      publishedService: "traefik/traefik"

ingressClass:
  enabled: true
  isDefaultClass: true
  name: traefik

ingressRoute:
  dashboard:
    enabled: true
    matchRule: Host(`barista503.cbrz.app`)
    entryPoints:
      - web

gateway:
  listeners:
    web:
      namespacePolicy:
        from: All
