apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: ip-address-pool-tailscale
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  addresses:
  - 100.70.15.42/32
