apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: metallb
    repo: https://metallb.github.io/metallb
    releaseName: metallb

resources:
  - l2-advertisment.yaml
  - ip-address-pool.yaml
  #- l2-advertisment-tailscale.yaml
  #- ip-address-pool-tailscale.yaml
