apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: traefik
    repo: https://metallb.github.io/metallb'
    version: 0.16.1
    releaseName: metallb

resources:
  - l2-advertisment.yaml
