apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cbrz-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'git@github.com:pablo-puyat/maraming.git'
    targetRevision: main
    path: k8s/overlays/prod
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: cbrz
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: postgresql.cnpg.io
      kind: Cluster
      jsonPointers:
        - /spec/maxSyncReplicas
        - /spec/minSyncReplicas
        - /spec/managed/roles
