apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: doppler-operator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://helm.doppler.com'
    chart: doppler-kubernetes-operator
    targetRevision: 1.7.1
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: doppler-operator-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
