apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeshark
  namespace: argocd # Assuming ArgoCD is in this namespace
spec:
  project: default
  source:
    repoURL: 'https://helm.kubeshark.co'
    targetRevision: 53.3.0
    chart: kubeshark
    helm:
      valueFiles:
        - ../overlays/kubeshark/values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kubeshark # Ensure this namespace exists
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
