apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeshark
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: 'git@github.com:pablo-puyat/cluster-state.git'
      targetRevision: HEAD
      ref: values
    - repoURL: 'https://helm.kubeshark.com'
      chart: kubeshark
      targetRevision: 53.3.0
      helm:
        valueFiles:
          - $values/overlays/kubeshark/values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kubeshark
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
