apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cbrz-argocd.yaml
  - cloudnative-pg-argocd.yaml
  - doppler-operator-argocd.yaml
  - metallb-argocd.yaml
  - metrics-server-argocd.yaml
  - monitoring-argocd.yaml
  - static-files-argocd.yaml
  - traefik-private-argocd.yaml
  - traefik-public-argocd.yaml

patches:
  - target:
      kind: Deployment
      name: argocd-repo-server
      namespace: argocd
    patch: |
      - op: add
        path: /spec/template/spec/hostNetwork
        value: true
      - op: add
        path: /spec/template/spec/dnsPolicy
        value: ClusterFirstWithHostNet
