apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-private
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/pablo-puyat/infrastructure.git'
    targetRevision: feat-monitoring
    path: gitops/infrastructure/traefik-private
    kustomize:
      version: v5
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: traefik-private
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
