apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: traefik
spec:
  project: default
  source:
    repoURL: 'git@github.com:pablo-puyat/cluster-state.git'
    targetRevision: HEAD
    path: overlays/traefik-public
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
